django/monitoring/urls.py
from django.urls import path

from . import views

app_name = 'monitoring'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:host_id>', views.detail, name='detail'),
    path('<int:host_id>/memory/', views.memory_events, name='memory_events'),
    path('<int:host_id>/disk/', views.disk_events, name='disk_events'),
    path('<int:host_id>/cpu/', views.cpu_events, name='cpu_events'),
    path('<int:host_id>/proc/', views.proc_events, name='proc_events'),
]

django/ruth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('monitoring/', include('monitoring.urls')),
    path('admin/', admin.site.urls),
]

django/monitoring/models.py
import json
from typing import List

import redis
from django.db import models

from .utils import DateObj


def parse_json(json_str: str) -> dict:
    return json.loads(json_str.decode('utf8').replace("'", '"'))


class Host(models.Model):
    host_id = models.IntegerField()
    host_name = models.CharField(max_length=200)

    def get_redis_key(self, perip: str) -> str:
        return f'host:{self.host_id}:{perip}'

    # todo move to utils
    def get_redis_instance(self) -> redis.StrictRedis:
        return redis.StrictRedis(host='redis', port=6379, db=0)

    def get_last_perip_state(self, perip: str):
        redis_key = self.get_redis_key(perip)
        r = self.get_redis_instance()
        return [parse_json(disk) for disk in r.zrange(redis_key, -1, -1)]

    def get_perip_events(self, perip: str, time_from: DateObj, time_to: DateObj) -> List[List[dict]]:
        redis_key = self.get_redis_key(perip)
        r = self.get_redis_instance()

        events: List[List[dict]] = []
        for events_json, ts in r.zrangebyscore(redis_key, time_from.timestamp(), time_to.timestamp(), withscores=True):
            e_list: dict = parse_json(events_json)
            # append timestamps
            for e in e_list:
                e['timestamp'] = int(ts)
            events.append(e_list)
        return events

    def __str__(self) -> str:
        return self.host_name

django/monitoring/forms.py
from django import forms


class DateRangePickerForm(forms.Form):
    time_range = forms.DateTimeField(widget=forms.TextInput(attrs={'class': 'datepicker'}))

django/monitoring/views.py
from datetime import datetime, timedelta
from typing import List, Tuple

import pandas as pd
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .forms import DateRangePickerForm
from .models import Host
from .utils import BokehGraphs, EventsConverter, DateObj, SizeObj

DATE_FORMAT = '%Y-%m-%d %I:%M %p'


# HOST PAGES

def index(request) -> HttpResponse:
    hosts: Host = Host.objects.all()
    return render(request, 'monitoring/index.html', {'hosts': hosts})


def detail(request, host_id: int) -> HttpResponse:
    host: Host = get_object_or_404(Host, pk=host_id)
    return render(request, 'monitoring/detail.html', {'host': host})


# MEMORY MONITORING VIEWS

def memory_events(request, host_id: int) -> HttpResponse:
    host: Host = get_object_or_404(Host, pk=host_id)
    perip: str = 'mem'
    events, from_dt, to_dt, templ_data = __get_perip_view_data(host, perip, request)

    if events:
        templ_data['ram_events_graph'] = BokehGraphs.get_line_graph(events, 'usedRam', 0, 'totalRam', from_dt, to_dt,
                                                                    title='Memory usage')
        templ_data['swap_events_graph'] = BokehGraphs.get_line_graph(events, 'usedSwap', 0, 'totalSwap', from_dt, to_dt,
                                                                     title='Swap usage')
    return render(request, 'monitoring/memory.html', templ_data)



# DISK MONITORING EVENTS

def disk_events(request, host_id: int) -> HttpResponse:
    host: Host = get_object_or_404(Host, pk=host_id)
    perip: str = 'disk'
    events, from_dt, to_dt, templ_data = __get_perip_view_data(host, perip, request)

    # last_disks_event: List[dict] = host.get_last_perip_state(perip)
    if events:
        templ_data['disk_events_graph'] = BokehGraphs.get_line_graph(events, 'used', 0, 'total', from_dt, to_dt,
                                                                     data_group_key='device', title='Disk usage')
        # templ_data['disk_current_state'] = BokehGraphs.get_hbars(last_disks_event, 'diskUsed', 'diskSize', title='Current disk state')
    return render(request, 'monitoring/disk.html', templ_data)


# CPU MONITORING EVENTS

def cpu_events(request, host_id: int) -> HttpResponse:
    host: Host = get_object_or_404(Host, pk=host_id)
    perip: str = 'cpu'
    events, from_dt, to_dt, templ_data = __get_perip_view_data(host, perip, request)

    if events:
        templ_data['cpu_events_graph'] = BokehGraphs.get_line_graph(events, 'cpuLoad', 0,
                                                                    SizeObj.get_percent_size(100), from_dt, to_dt,
                                                                    title='CPU usage')
    return render(request, 'monitoring/cpu.html', templ_data)


# PROC MONITORING EVENTS

def proc_events(request, host_id: int) -> HttpResponse:
    host: Host = get_object_or_404(Host, pk=host_id)
    perip: str = 'proc'
    events, from_dt, to_dt, templ_data = __get_perip_view_data(host, perip, request)

    if events:
        df: pd.DataFrame = pd.DataFrame([event for event_list in events for event in event_list])

        df = df.groupby(['pid', 'name', 'cmdline']).agg(
            {'ppid': 'first', 'username': 'first', 'nice': 'first', 'memory_percent': 'mean',
             'cpu_percent': 'mean'}).reset_index()
        df.set_index('pid')

        # todo add nice, create time as dateobj, ppid, username
        templ_data['proc_list'] = df.to_html()

    return render(request, 'monitoring/proc.html', templ_data)

# HELPER METHODS

def __get_range_params(request) -> Tuple[DateObj, DateObj]:
    range_str = request.GET.get('time_range')
    if range_str:
        ranges: List[DateObj] = [DateObj.from_str(date_str) for date_str in range_str.split('  -  ')]
        return ranges[0], ranges[1]
    now_dt = datetime.now().replace(second=0, microsecond=0)

    return DateObj((now_dt - timedelta(hours=1)).timestamp()), DateObj(now_dt.timestamp())


def __get_perip_view_data(host: Host, perip: str, request):
    form = DateRangePickerForm()
    from_dt, to_dt = __get_range_params(request)

    events = host.get_perip_events(perip, from_dt, to_dt)
    events = EventsConverter.convert_values(events) if events else None

    templ_data: dict = {'host': host, 'events': events, 'form': form, 'from_dt': str(from_dt),
                        'to_dt': str(to_dt)}
    return events, from_dt, to_dt, templ_data

django/monitoring/templates/monitoring/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Ruth{% endblock %}</title>
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-0.13.0.min.css" rel="stylesheet" type="text/css">
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.13.0.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
    <style>
        .datepicker {
            width: 300px;
        }
    </style>
</head>
<body>
{% block content %}{% endblock %}
</body>
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.13.0.min.js"></script>
<script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.13.0.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script>
    $('.datepicker').daterangepicker({
        "timePicker": true,
        ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Last 7 Days': [moment().subtract(6, 'days'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        "locale": {
            "format": "YYYY-MM-DD hh:mm A",
            "separator": "  -  ",
            "applyLabel": "Apply",
            "cancelLabel": "Cancel",
            "fromLabel": "From",
            "toLabel": "To",
            "customRangeLabel": "Custom",
            "weekLabel": "W",
            "daysOfWeek": [
                "Su",
                "Mo",
                "Tu",
                "We",
                "Th",
                "Fr",
                "Sa"
            ],
            "monthNames": [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December"
            ],
            "firstDay": 1
        },
        "startDate": "{{ from_dt }}",
        "endDate": "{{ to_dt }}",
        "opens": "center"
    }, function (start, end, label) {
        console.log('New date range selected: ' + start.format('YYYY-MM-DD hh:mm A') + ' to ' + end.format('YYYY-MM-DD hh:mm A') + ' (predefined range: ' + label + ')');
    });
</script>
<script>
    $('.dataframe').DataTable();
</script>
{% block scripts %}{% endblock %}
</html>

django/monitoring/templates/monitoring/cpu.html
{% extends 'monitoring/base.html' %}

{% block content %}
    <p>Memory monitoring info for host: {{ host.host_name }}</p>
    {% if form %}
        <form action="{% url 'monitoring:cpu_events' host.id %}" method="get">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
        </form>
    {% endif %}
    {% if cpu_events_graph.div %}
        <div class="monitor-graph">
            {{ cpu_events_graph.div | safe }}
        </div>
    {% endif %}
    {% if events %}
        <p>Number of events: {{ events|length }}</p>
    {% else %}
        <p>No events available</p>
    {% endif %}
{% endblock %}

{% block scripts %}
    {% if cpu_events_graph.script %}
        {{ cpu_events_graph.script | safe }}
    {% endif %}
{% endblock %}

django/monitoring/templates/monitoring/detail.html
{% extends 'monitoring/base.html' %}

{% block content %}
    <ul>
        <li><h2>{{ host.host_name }}</h2></li>
        <ul>
            <li><a href="{% url 'monitoring:memory_events' host.id %}">memory</a></li>
            <li><a href="{% url 'monitoring:disk_events' host.id %}">disks</a></li>
            <li><a href="{% url 'monitoring:cpu_events' host.id %}">cpu</a></li>
            <li><a href="{% url 'monitoring:proc_events' host.id %}">processes</a></li>
        </ul>
    </ul>
{% endblock %}

django/monitoring/templates/monitoring/disk.html
{% extends 'monitoring/base.html' %}

{% block content %}
    <p>Disk monitoring info for host: {{ host.host_name }}</p>
    {% if form %}
        <form action="{% url 'monitoring:disk_events' host.id %}" method="get">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
        </form>
    {% endif %}
    {% if disk_events_graph.div %}
        <div class="monitor-graph">
            {{ disk_events_graph.div | safe }}
        </div>
    {% endif %}
    {% if disk_current_state.div %}
        <div class="monitor-graph">
            {{ disk_current_state.div | safe }}
        </div>
    {% endif %}
    {% if events %}
        <p>Number of events: {{ events|length }}</p>
    {% else %}
        <p>No events available</p>
    {% endif %}
{% endblock %}

{% block scripts %}
    {% if disk_events_graph.script %}
        {{ disk_events_graph.script | safe }}
    {% endif %}
    {% if disk_current_state.script %}
        {{ disk_current_state.script | safe }}
    {% endif %}
{% endblock %}

django/monitoring/templates/monitoring/index.html
{% extends 'monitoring/base.html' %}

{% block content %}
    {% if hosts %}
        {% for host in hosts %}
            <h2><a href="{% url 'monitoring:detail' host.id %}">{{ host.host_name }}</a></h2>
        {% endfor %}
    {% else %}
        <p>No hosts are available.</p>
    {% endif %}
{% endblock %}

django/monitoring/templates/monitoring/memory.html
{% extends 'monitoring/base.html' %}

{% block content %}
    <p>Memory monitoring info for host: {{ host.host_name }}</p>
    {% if form %}
        <form action="{% url 'monitoring:memory_events' host.id %}" method="get">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
        </form>
    {% endif %}
    {% if ram_events_graph.div %}
        <div class="monitor-graph">
            {{ ram_events_graph.div | safe }}
        </div>
    {% endif %}
    {% if swap_events_graph.div %}
        <div class="monitor-graph">
            {{ swap_events_graph.div | safe }}
        </div>
    {% endif %}
    {% if events %}
        <p>Number of events: {{ events|length }}</p>
    {% else %}
        <p>No events available</p>
    {% endif %}
{% endblock %}

{% block scripts %}
    {% if ram_events_graph.script %}
        {{ ram_events_graph.script | safe }}
    {% endif %}
    {% if swap_events_graph.script %}
        {{ swap_events_graph.script | safe }}
    {% endif %}
{% endblock %}

django/monitoring/templates/monitoring/proc.html
{% extends 'monitoring/base.html' %}

{% block content %}
    <p>Process monitoring info for host: {{ host.host_name }}</p>
    {% if form %}
        <form action="{% url 'monitoring:cpu_events' host.id %}" method="get">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
        </form>
    {% endif %}

    {% if proc_list %} {{ proc_list|safe }} {% endif %}

    {% if events %}
        <p>Number of events: {{ events|length }}</p>
    {% else %}
        <p>No events available</p>
    {% endif %}
{% endblock %}
{% block scripts %}{% endblock %}